export interface CategoryContent {
  key: string;
  label: string;
  name: string;
  title: string;
  company: string;
  phone: string;
  email: string;
  website: string;
  address: string;
  palette: [string, string, string]; // primary, secondary, ink/neutral
  headingFont: string;
  bodyFont: string;
}

export const CATEGORIES: CategoryContent[] = [
  { key: "real-estate", label: "Real Estate", name: "Dana Whitfield", title: "Realtor", company: "Whitfield & Co. Realty", phone: "(816) 555-0142", email: "dana@whitfieldrealty.com", website: "whitfieldrealty.com", address: "412 Main St, Kansas City, MO", palette: ["#123C69", "#C9A24B", "#111111"], headingFont: "Playfair Display", bodyFont: "Inter" },
  { key: "construction", label: "Construction", name: "Marcus Reilly", title: "General Contractor", company: "Reilly Construction Co.", phone: "(816) 555-0198", email: "marcus@reillybuilds.com", website: "reillybuilds.com", address: "88 Industrial Pkwy, KCMO", palette: ["#D9531E", "#1B1B1B", "#F4F1EC"], headingFont: "Oswald", bodyFont: "Inter" },
  { key: "roofing", label: "Roofing", name: "Tom Baxter", title: "Owner", company: "Baxter Roofing & Exteriors", phone: "(913) 555-0110", email: "tom@baxterroofing.com", website: "baxterroofing.com", address: "205 Shingle Rd, Overland Park, KS", palette: ["#2B2D42", "#EF233C", "#F5F5F5"], headingFont: "Oswald", bodyFont: "Roboto" },
  { key: "plumbing", label: "Plumbing", name: "Carla Nguyen", title: "Master Plumber", company: "Nguyen Plumbing & Drain", phone: "(816) 555-0176", email: "carla@nguyenplumbing.com", website: "nguyenplumbing.com", address: "77 Pipeline Ave, KCMO", palette: ["#0B6E4F", "#0A3D62", "#FFFFFF"], headingFont: "Montserrat", bodyFont: "Inter" },
  { key: "electrical", label: "Electrical", name: "Devon Marsh", title: "Licensed Electrician", company: "Marsh Electric", phone: "(816) 555-0133", email: "devon@marshelectric.com", website: "marshelectric.com", address: "19 Volt St, KCMO", palette: ["#F2B705", "#1C1C1C", "#FFFFFF"], headingFont: "Space Grotesk", bodyFont: "Inter" },
  { key: "landscaping", label: "Landscaping", name: "Renee Ford", title: "Owner", company: "Ford Landscape Design", phone: "(913) 555-0184", email: "renee@fordlandscape.com", website: "fordlandscape.com", address: "500 Garden Way, Overland Park, KS", palette: ["#2D6A4F", "#95D5B2", "#1B1B1B"], headingFont: "Merriweather", bodyFont: "Inter" },
  { key: "cleaning", label: "Cleaning Services", name: "Priya Shah", title: "Founder", company: "Shah Sparkle Cleaning Co.", phone: "(816) 555-0121", email: "priya@sparklecleanco.com", website: "sparklecleanco.com", address: "33 Fresh Ln, KCMO", palette: ["#3DA5D9", "#EAF6FF", "#0B2545"], headingFont: "Poppins", bodyFont: "Inter" },
  { key: "automotive", label: "Automotive", name: "Ray Delgado", title: "Shop Owner", company: "Delgado Auto Repair", phone: "(816) 555-0155", email: "ray@delgadoauto.com", website: "delgadoauto.com", address: "1200 Torque Rd, KCMO", palette: ["#1B1B1B", "#E63946", "#F1FAEE"], headingFont: "Oswald", bodyFont: "Roboto" },
  { key: "restaurant", label: "Restaurants & Catering", name: "Sofia Ricci", title: "Chef & Owner", company: "Ricci Table Catering", phone: "(816) 555-0167", email: "sofia@riccitable.com", website: "riccitable.com", address: "64 Basil St, KCMO", palette: ["#7A1E1E", "#F2E8CF", "#1B1B1B"], headingFont: "Playfair Display", bodyFont: "Lora" },
  { key: "beauty-salon", label: "Beauty & Salon", name: "Amara Belle", title: "Stylist & Owner", company: "Belle Studio Salon", phone: "(913) 555-0143", email: "amara@bellestudio.com", website: "bellestudio.com", address: "9 Blush Ave, Overland Park, KS", palette: ["#D4A5A5", "#3E2C2C", "#FFF7F5"], headingFont: "Playfair Display", bodyFont: "Poppins" },
  { key: "healthcare", label: "Healthcare", name: "Dr. Alan Okafor", title: "Family Physician", company: "Okafor Family Health", phone: "(816) 555-0109", email: "aokafor@okaforhealth.com", website: "okaforhealth.com", address: "455 Wellness Blvd, KCMO", palette: ["#0B7285", "#E7F5F8", "#12232E"], headingFont: "Merriweather", bodyFont: "Inter" },
  { key: "dental", label: "Dental", name: "Dr. Lisa Chen", title: "Dentist, DDS", company: "Chen Family Dental", phone: "(913) 555-0128", email: "info@chenfamilydental.com", website: "chenfamilydental.com", address: "3200 Smile Way, Overland Park, KS", palette: ["#2C7A7B", "#EAFBFB", "#173F3F"], headingFont: "Montserrat", bodyFont: "Inter" },
  { key: "legal", label: "Legal", name: "James Whitfield", title: "Managing Partner", company: "Whitfield Law Group", phone: "(816) 555-0175", email: "james@whitfieldlaw.com", website: "whitfieldlaw.com", address: "700 Courthouse Sq, KCMO", palette: ["#111827", "#B08D57", "#F5F4F0"], headingFont: "Playfair Display", bodyFont: "Inter" },
  { key: "accounting", label: "Accounting & Finance", name: "Nora Patel", title: "CPA", company: "Patel Accounting Group", phone: "(816) 555-0161", email: "nora@patelcpa.com", website: "patelcpa.com", address: "88 Ledger Ln, KCMO", palette: ["#0A3D62", "#60A3D9", "#F5F7FA"], headingFont: "Roboto", bodyFont: "Inter" },
  { key: "insurance", label: "Insurance", name: "Greg Hoffman", title: "Insurance Agent", company: "Hoffman Insurance Partners", phone: "(913) 555-0139", email: "greg@hoffmanins.com", website: "hoffmanins.com", address: "14 Assurance Dr, Overland Park, KS", palette: ["#1D3557", "#457B9D", "#F1FAEE"], headingFont: "Montserrat", bodyFont: "Inter" },
  { key: "technology", label: "Technology", name: "Zoe Kim", title: "Founder & CEO", company: "Kimwave Technologies", phone: "(816) 555-0117", email: "zoe@kimwave.io", website: "kimwave.io", address: "100 Innovation Dr, KCMO", palette: ["#5B21B6", "#111827", "#F5F3FF"], headingFont: "Space Grotesk", bodyFont: "Inter" },
  { key: "creative-agency", label: "Creative Agency", name: "Theo Marsh", title: "Creative Director", company: "Marsh & Co. Studio", phone: "(816) 555-0104", email: "theo@marshstudio.co", website: "marshstudio.co", address: "21 Palette St, KCMO", palette: ["#FF6B35", "#004E89", "#FFF8F0"], headingFont: "Poppins", bodyFont: "Space Grotesk" },
  { key: "photography", label: "Photography", name: "Isla Moreno", title: "Photographer", company: "Isla Moreno Photography", phone: "(913) 555-0192", email: "isla@islamoreno.com", website: "islamoreno.com", address: "5 Aperture Ave, Overland Park, KS", palette: ["#1B1B1B", "#D8CAB8", "#FFFFFF"], headingFont: "Prata", bodyFont: "Inter" },
  { key: "consulting", label: "Consulting", name: "Ben Carver", title: "Principal Consultant", company: "Carver Strategy Partners", phone: "(816) 555-0186", email: "ben@carverstrategy.com", website: "carverstrategy.com", address: "900 Advisory Way, KCMO", palette: ["#0F172A", "#94A3B8", "#F8FAFC"], headingFont: "Raleway", bodyFont: "Inter" },
  { key: "general-corporate", label: "General Corporate", name: "Alicia Nguyen", title: "Director of Operations", company: "Bloom Corporate Group", phone: "(816) 555-0150", email: "alicia@bloomcorp.com", website: "bloomcorp.com", address: "300 Enterprise Blvd, KCMO", palette: ["#0A6E63", "#F2B705", "#111111"], headingFont: "Inter", bodyFont: "Inter" },

  // Trades and consumer services, added for breadth: each category yields five layouts, so the
  // gallery covers the businesses a print shop is actually asked for rather than twenty office
  // trades. Fonts are drawn from EDITOR_FONTS only - anything else silently falls back to Helvetica
  // in the PDF - and each palette is [primary, secondary, ink/neutral] with enough separation to
  // stay legible at card size.
  { key: "hvac", label: "HVAC", name: "Dale Brennan", title: "HVAC Technician", company: "Brennan Heating & Air", phone: "(816) 555-0207", email: "dale@brennanhvac.com", website: "brennanhvac.com", address: "142 Furnace Rd, KCMO", palette: ["#1F4E79", "#E8641B", "#F4F6F8"], headingFont: "Barlow Condensed", bodyFont: "Inter" },
  { key: "painting", label: "Painting & Drywall", name: "Hector Alvarez", title: "Owner", company: "Alvarez Painting Co.", phone: "(913) 555-0214", email: "hector@alvarezpainting.com", website: "alvarezpainting.com", address: "60 Primer St, Overland Park, KS", palette: ["#2B4162", "#E0B44A", "#FAF7F2"], headingFont: "Work Sans", bodyFont: "Inter" },
  { key: "handyman", label: "Handyman", name: "Wes Turner", title: "Handyman", company: "Turner Home Repair", phone: "(816) 555-0223", email: "wes@turnerrepair.com", website: "turnerrepair.com", address: "9 Toolbox Ln, KCMO", palette: ["#3E4C59", "#F0A202", "#FFFFFF"], headingFont: "Oswald", bodyFont: "Open Sans" },
  { key: "pest-control", label: "Pest Control", name: "Nina Alcott", title: "Licensed Technician", company: "Alcott Pest Solutions", phone: "(816) 555-0231", email: "nina@alcottpest.com", website: "alcottpest.com", address: "77 Cedar Ct, KCMO", palette: ["#14532D", "#84CC16", "#F7FEE7"], headingFont: "Montserrat", bodyFont: "Inter" },
  { key: "pool-service", label: "Pool & Spa Service", name: "Cody Rains", title: "Service Manager", company: "Rains Pool & Spa", phone: "(913) 555-0248", email: "cody@rainspool.com", website: "rainspool.com", address: "310 Poolside Dr, Overland Park, KS", palette: ["#0369A1", "#7DD3FC", "#0B3B54"], headingFont: "Poppins", bodyFont: "Inter" },
  { key: "solar", label: "Solar & Energy", name: "Priyanka Rao", title: "Energy Consultant", company: "Rao Solar Group", phone: "(816) 555-0256", email: "priyanka@raosolar.com", website: "raosolar.com", address: "500 Sunfield Way, KCMO", palette: ["#0F766E", "#FBBF24", "#0B2D2A"], headingFont: "Space Grotesk", bodyFont: "Inter" },
  { key: "moving", label: "Moving & Storage", name: "Andre Cole", title: "Operations Lead", company: "Cole Moving & Storage", phone: "(816) 555-0264", email: "andre@colemoving.com", website: "colemoving.com", address: "1400 Crate Blvd, KCMO", palette: ["#1E293B", "#F97316", "#F8FAFC"], headingFont: "Anton", bodyFont: "Roboto" },
  { key: "trucking", label: "Trucking & Logistics", name: "Bill Krause", title: "Fleet Owner", company: "Krause Freight Lines", phone: "(816) 555-0272", email: "bill@krausefreight.com", website: "krausefreight.com", address: "8800 Depot Rd, KCMO", palette: ["#111827", "#DC2626", "#F3F4F6"], headingFont: "Bebas Neue", bodyFont: "Roboto" },
  { key: "security", label: "Security Services", name: "Marla Boyd", title: "Director of Security", company: "Boyd Protective Services", phone: "(913) 555-0289", email: "marla@boydprotective.com", website: "boydprotective.com", address: "24 Sentinel Way, Overland Park, KS", palette: ["#0B1220", "#3B82F6", "#E5E7EB"], headingFont: "Oswald", bodyFont: "Inter" },
  { key: "fitness", label: "Fitness & Training", name: "Jordan Pike", title: "Personal Trainer", company: "Pike Strength Studio", phone: "(816) 555-0295", email: "jordan@pikestrength.com", website: "pikestrength.com", address: "250 Barbell Ave, KCMO", palette: ["#111111", "#22D3EE", "#F5F5F5"], headingFont: "Anton", bodyFont: "Inter" },
  { key: "spa-massage", label: "Spa & Massage", name: "Lena Farrow", title: "Massage Therapist", company: "Farrow Wellness Spa", phone: "(913) 555-0303", email: "lena@farrowspa.com", website: "farrowspa.com", address: "18 Calm St, Overland Park, KS", palette: ["#5B6B5A", "#DCD3C3", "#2B2B2B"], headingFont: "Cormorant Garamond", bodyFont: "Nunito" },
  { key: "barber", label: "Barbershop", name: "Malik Reed", title: "Master Barber", company: "Reed & Sons Barbershop", phone: "(816) 555-0318", email: "malik@reedbarbers.com", website: "reedbarbers.com", address: "31 Fade St, KCMO", palette: ["#14110F", "#B5651D", "#F1E9DE"], headingFont: "Cinzel", bodyFont: "Inter" },
  { key: "tattoo", label: "Tattoo Studio", name: "Sable Cruz", title: "Tattoo Artist", company: "Ironwood Tattoo", phone: "(816) 555-0326", email: "sable@ironwoodtattoo.com", website: "ironwoodtattoo.com", address: "66 Needle St, KCMO", palette: ["#0A0A0A", "#B91C1C", "#E7E5E4"], headingFont: "Abril Fatface", bodyFont: "Work Sans" },
  { key: "bakery-cafe", label: "Bakery & Cafe", name: "Ivy Callahan", title: "Head Baker", company: "Callahan Bread House", phone: "(816) 555-0334", email: "ivy@callahanbread.com", website: "callahanbread.com", address: "7 Flour Mill Rd, KCMO", palette: ["#8C5A2B", "#F5E6D0", "#2E2119"], headingFont: "Lobster", bodyFont: "Lora" },
  { key: "florist", label: "Florist", name: "Rosa Lindqvist", title: "Floral Designer", company: "Lindqvist Flower Studio", phone: "(913) 555-0341", email: "rosa@lindqvistflowers.com", website: "lindqvistflowers.com", address: "12 Petal Ln, Overland Park, KS", palette: ["#6D466B", "#EFD9CE", "#2F2235"], headingFont: "Great Vibes", bodyFont: "Poppins" },
  { key: "veterinary", label: "Veterinary & Pet Care", name: "Dr. Owen Hartley", title: "Veterinarian", company: "Hartley Animal Clinic", phone: "(816) 555-0359", email: "owen@hartleyvet.com", website: "hartleyvet.com", address: "480 Paw Print Dr, KCMO", palette: ["#0E7490", "#FDE68A", "#0B3038"], headingFont: "Nunito", bodyFont: "Inter" },
  { key: "childcare", label: "Childcare & Early Learning", name: "Tasha Boone", title: "Center Director", company: "Little Prairie Learning", phone: "(913) 555-0367", email: "tasha@littleprairie.com", website: "littleprairie.com", address: "22 Sunny Ln, Overland Park, KS", palette: ["#2563EB", "#FBBF24", "#1C2B4A"], headingFont: "Josefin Sans", bodyFont: "Nunito" },
  { key: "tutoring", label: "Tutoring & Education", name: "Samuel Ade", title: "Academic Tutor", company: "Ade Learning Lab", phone: "(816) 555-0375", email: "samuel@adelearning.com", website: "adelearning.com", address: "140 Scholar St, KCMO", palette: ["#1E3A8A", "#93C5FD", "#F8FAFC"], headingFont: "Libre Baskerville", bodyFont: "Inter" },
  { key: "event-planning", label: "Event Planning", name: "Camille Oduya", title: "Event Planner", company: "Oduya Events", phone: "(816) 555-0383", email: "camille@oduyaevents.com", website: "oduyaevents.com", address: "310 Banquet Row, KCMO", palette: ["#4C1D95", "#E9D5FF", "#1F1235"], headingFont: "Raleway", bodyFont: "Inter" },
  { key: "wedding", label: "Weddings", name: "Elise Marchetti", title: "Wedding Coordinator", company: "Marchetti Weddings", phone: "(913) 555-0391", email: "elise@marchettiweddings.com", website: "marchettiweddings.com", address: "5 Chapel Ct, Overland Park, KS", palette: ["#7C6A5A", "#F3EDE4", "#2A241F"], headingFont: "Dancing Script", bodyFont: "Cormorant Garamond" },
  { key: "interior-design", label: "Interior Design", name: "Noor Haddad", title: "Interior Designer", company: "Haddad Interiors", phone: "(816) 555-0408", email: "noor@haddadinteriors.com", website: "haddadinteriors.com", address: "88 Atelier Ave, KCMO", palette: ["#3F3A36", "#C8B6A6", "#FAF6F1"], headingFont: "Prata", bodyFont: "Raleway" },
  { key: "architecture", label: "Architecture", name: "Victor Lang", title: "Principal Architect", company: "Lang Architecture", phone: "(816) 555-0416", email: "victor@langarch.com", website: "langarch.com", address: "1 Drafting Sq, KCMO", palette: ["#18181B", "#A1A1AA", "#FAFAFA"], headingFont: "Space Grotesk", bodyFont: "Work Sans" },
  { key: "marketing-agency", label: "Marketing & Advertising", name: "Dani Alvarez", title: "Account Director", company: "Northbound Marketing", phone: "(214) 555-0424", email: "dani@northboundmktg.com", website: "northboundmktg.com", address: "2100 Commerce St, Dallas, TX", palette: ["#DB2777", "#0F172A", "#FDF2F8"], headingFont: "Poppins", bodyFont: "Inter" },
  { key: "nonprofit", label: "Nonprofit & Community", name: "Grace Whitlock", title: "Executive Director", company: "Riverbend Community Fund", phone: "(816) 555-0432", email: "grace@riverbendfund.org", website: "riverbendfund.org", address: "45 Union Hall, KCMO", palette: ["#166534", "#FDE047", "#0E2A18"], headingFont: "Merriweather", bodyFont: "Open Sans" },
  { key: "church", label: "Church & Ministry", name: "Ruth Ellery", title: "Lead Pastor", company: "Cornerstone Fellowship", phone: "(913) 555-0449", email: "ruth@cornerstonefellowship.org", website: "cornerstonefellowship.org", address: "700 Chapel Hill Rd, Overland Park, KS", palette: ["#4A3F35", "#D6C7A1", "#FBF9F4"], headingFont: "Cinzel", bodyFont: "Lora" },
];

export const STYLE_TAGS = ["minimal", "modern", "luxury", "bold", "corporate", "elegant", "geometric", "friendly", "industrial", "creative"] as const;
export type StyleTag = (typeof STYLE_TAGS)[number];
