/**
 * Phase 5: the trade and profession categories the older vector template library covered but the
 * photographic set did not, so every category in the browse tree has photo cards rather than only
 * the 45 that happened to be generated first.
 */

import type { BedCategory } from "./card-bed-categories";

const c = (slug: string, label: string, palette: string, subjects: string[]): BedCategory =>
  ({ slug, label, phase: 5 as unknown as BedCategory["phase"], palette, subjects });

export const TRADE_CATEGORIES: BedCategory[] = [
  c("barber", "Barber", "deep charcoal, warm brass, cream and oxblood", [
    "a shaving brush and bowl on dark marble", "barber scissors and comb on leather",
    "a classic barber chair in a warm interior", "a straight razor beside a folded towel",
    "hair clippers on a dark counter", "a barber pole in soft evening light",
    "shaving soap lather in a ceramic bowl", "a wall of grooming bottles on wood shelving",
    "a mirror and brass fittings in a barbershop", "combs in a jar of blue barbicide",
  ]),
  c("childcare", "Child Care", "friendly primary blue, sunny yellow, grass green and cream", [
    "soft wooden toy blocks on a pale rug", "a bright nursery corner with cushions",
    "small painted handprints on paper", "stuffed animals lined on a low shelf",
    "chunky crayons in a tin", "a sunny playroom with low tables",
    "a child's painting drying on an easel", "colourful stacking rings on a mat",
    "picture books in a low basket", "a cot with soft muslin blankets",
  ]),
  c("hvac", "Heating & Air", "cool steel blue, safety orange, slate and white", [
    "an outdoor condenser unit against a clean wall", "a technician's gauges on a manifold",
    "a ceiling vent in a bright modern room", "ductwork running through a clean loft",
    "a thermostat on a pale wall", "a furnace interior with visible burners",
    "a heat pump in golden hour light", "insulated pipe runs in a plant room",
    "an air filter being replaced, close up", "frost patterns on a coil, macro",
  ]),
  c("tattoo", "Tattoo", "ink black, deep crimson, bone and steel", [
    "a tattoo machine on a black cloth", "ink caps arranged in a row",
    "a sketchbook of line drawings on a dark desk", "a clean tattoo studio chair",
    "sterile needles in packaging on black", "neon signage glow in a dark studio",
    "gloved hands preparing a stencil", "a wall of flash art in soft focus",
    "black ink swirling in water", "a leather portfolio on a dark counter",
  ]),
  c("florist", "Florist", "soft blush, deep sage, cream and terracotta", [
    "a florist bench with cut stems and twine", "buckets of fresh blooms in a shop",
    "hands wrapping a bouquet in kraft paper", "ranunculus and anemones on white linen",
    "dried bunches hanging to cure", "a flower market stall in morning light",
    "secateurs and ribbon on a wooden bench", "peonies in a glass vase by a window",
    "eucalyptus and roses laid on marble", "a shopfront awning with flower displays",
  ]),
  c("veterinary", "Veterinary", "calm teal, clean white, warm sand and slate", [
    "a bright clean veterinary exam room", "a stethoscope beside a dog's paw",
    "a cat being gently held by gloved hands", "veterinary instruments on a sterile tray",
    "a puppy on a soft blanket in daylight", "a clinic reception with plants",
    "a horse being examined in a stable", "medical charts and a tablet on white",
    "a rabbit in soft focus on a towel", "a calm dog waiting in a bright corridor",
  ]),
  c("wedding", "Wedding", "champagne gold, ivory, blush and deep sage", [
    "a set banquet table with candles at dusk", "a floral arch against soft greenery",
    "wedding rings on textured linen", "string lights over an evening reception",
    "a bridal bouquet on a pale bench", "champagne flutes catching warm light",
    "a lace veil in soft window light", "an aisle lined with petals",
    "a tiered cake on a styled table", "confetti caught mid air against dark",
  ]),
  c("fitness", "Fitness", "energetic lime, deep charcoal, electric blue and white", [
    "a loaded barbell on a gym floor", "running shoes on a track at sunrise",
    "dumbbells racked in a modern gym", "a rolled yoga mat in a bright studio",
    "a kettlebell in dramatic side light", "a spin studio with warm uplighting",
    "a rowing machine in shallow focus", "chalked hands gripping a bar",
    "a stopwatch and skipping rope", "an empty gym at dawn with long shadows",
  ]),
  c("photography", "Photography", "ink black, warm grey, bone and amber", [
    "a camera body and prime lens on dark wood", "a lit studio backdrop and light stand",
    "35mm film rolls scattered on a table", "a darkroom with red safelight",
    "a lens aperture blade macro", "a tripod silhouetted against sunset",
    "contact sheets on a light box", "a camera bag with lenses laid out",
    "soft window light across a plain wall", "a vintage rangefinder on leather",
  ]),
  c("dental", "Dental", "clinical teal, crisp white, soft grey and mint", [
    "a bright modern dental surgery", "dental instruments on a sterile tray",
    "a clean treatment chair by a window", "an orthodontic model on white",
    "gloved hands holding a small mirror", "a calm dental reception area",
    "a toothbrush and floss on white marble", "an x-ray viewer in soft light",
    "a sterilisation tray in clean light", "a bright corridor in a dental clinic",
  ]),
  c("legal", "Legal", "deep burgundy, navy, parchment and antique brass", [
    "law books on a dark shelf", "a fountain pen on a signed document",
    "classical courthouse columns", "a formal boardroom with leather chairs",
    "scales of justice in silhouette", "a wooden gavel on a bench",
    "marble steps and brass railings", "an office desk with reading glasses",
    "a bound legal volume open on a desk", "a quiet office with tall bookcases",
  ]),
  c("accounting", "Accounting", "deep navy, forest green, warm grey and brass", [
    "a ledger and calculator on walnut", "an upward line graph on dark paper",
    "stacked coins in shallow focus", "a fountain pen resting on a spreadsheet",
    "a clean desk with laptop and coffee", "a glass office tower at dusk",
    "receipts and a pen on a pale desk", "a calculator keypad macro",
    "filing drawers in warm light", "a quiet office with a city view",
  ]),
  c("insurance", "Insurance", "trust blue, warm grey, bone and deep green", [
    "a family home exterior in soft daylight", "an umbrella against a grey sky",
    "hands holding a paper house cutout", "a car parked outside a suburban house",
    "a clean office desk with documents", "a modern office building facade",
    "a handshake in a bright room", "keys resting on a signed document",
    "a calm reception area with plants", "soft light through office blinds",
  ]),
  c("technology", "Technology", "cool slate, electric blue, off-black and white", [
    "a server rack with status lights", "a circuit board macro in cool light",
    "a laptop on a minimal desk", "fibre optic strands glowing",
    "a clean workspace with dual monitors", "abstract data visualisation on dark",
    "a network switch with patch cables", "a smartphone on brushed aluminium",
    "soft blue light across a keyboard", "a modern office with glass partitions",
  ]),
  c("consulting", "Consulting", "deep navy, warm grey, burgundy and brass", [
    "a bright boardroom with a long table", "a whiteboard with abstract diagrams",
    "a leather notebook and pen on walnut", "a city skyline from an office window",
    "hands shaking across a table", "an architectural corporate lobby",
    "a laptop and coffee on a minimal desk", "stacked reports and glasses",
    "an empty meeting room in morning light", "glass office tower from below",
  ]),
  c("architecture", "Architecture", "concrete grey, bone, deep ink and burnt orange", [
    "rolled blueprints on a drafting table", "a scale model of a building",
    "a concrete stairwell with hard shadow", "a modern facade with clean lines",
    "drafting tools on a white desk", "a glass atrium from below",
    "a brutalist wall in raking light", "an architect's sketch on tracing paper",
    "a building under construction against sky", "a minimal interior with tall windows",
  ]),
  c("interior-design", "Interior Design", "warm bone, deep olive, terracotta and brass", [
    "fabric swatches fanned on a table", "a styled living room in soft daylight",
    "paint chips and tile samples", "a mood board with textures pinned",
    "a designer chair against a plain wall", "brass fittings on a walnut cabinet",
    "layered rugs and cushions in warm light", "a bright hallway with arched doorway",
    "curtains diffusing morning light", "a marble countertop with ceramics",
  ]),
  c("painting", "Painting & Decorating", "clean white, sky blue, warm grey and yellow", [
    "a paint roller on a freshly coated wall", "brushes resting on a paint tin",
    "colour swatch cards fanned out", "a decorator's ladder in an empty room",
    "masking tape along clean trim", "a freshly painted bright interior",
    "paint pouring into a tray, macro", "a dust sheet over furniture in daylight",
    "a wall half painted showing the line", "brushes soaking in a jar",
  ]),
  c("handyman", "Handyman", "workshop amber, deep charcoal, steel and cream", [
    "a leather tool belt on a workbench", "assorted hand tools laid out neatly",
    "a cordless drill on sawn timber", "a spirit level on a new frame",
    "screws and fixings in a tray", "a tidy garage workshop wall",
    "hands measuring timber with a tape", "a hammer resting on a plank",
    "sawdust caught in a shaft of light", "a toolbox open on a concrete floor",
  ]),
  c("pest-control", "Pest Control", "clean green, deep charcoal, white and amber", [
    "a technician's sprayer against a clean wall", "a tidy suburban house exterior",
    "a sealed doorway threshold detail", "protective gloves and equipment on white",
    "a clean kitchen with nothing on the counter", "a garden boundary in bright daylight",
    "an inspection torch on a dark floor", "a clean loft space with light beams",
    "a spotless pantry shelf", "a home exterior with tidy landscaping",
  ]),
  c("pool-service", "Pool Service", "aqua blue, crisp white, sand and deep teal", [
    "sunlight rippling across clear pool water", "a pool skimmer resting on the edge",
    "a clean tiled pool edge, macro", "a backyard pool at golden hour",
    "water droplets on blue tile", "pool chemicals arranged neatly on white",
    "a lounger beside still water", "a pool cleaner robot underwater",
    "steps descending into clear water", "a pool at dusk with underwater lighting",
  ]),
  c("solar", "Solar", "deep sky blue, sunny amber, slate and white", [
    "solar panels on a roof against blue sky", "a panel array in golden hour light",
    "an inverter mounted on a clean wall", "sunlight reflecting off panel glass",
    "an aerial view of a solar array", "a technician's hands on a panel frame",
    "panel cells in extreme macro", "a house roof with panels at dusk",
    "a battery unit in a tidy garage", "clouds reflected in panel glass",
  ]),
  c("moving", "Moving", "kraft brown, deep navy, white and safety orange", [
    "stacked cardboard boxes in an empty room", "a moving truck with its door open",
    "a hand truck loaded with boxes", "packing tape and a marker on kraft",
    "an empty room with sunlight on floorboards", "furniture wrapped in moving blankets",
    "keys handed over on a doorstep", "a loading ramp at a house",
    "bubble wrap texture in macro", "a labelled box on a wooden floor",
  ]),
  c("trucking", "Trucking", "steel blue, safety yellow, asphalt grey and chrome", [
    "a haulage truck on an open highway at dusk", "a chrome exhaust stack against sky",
    "a truck cab interior at night", "a depot with trucks lined at dawn",
    "a trailer being loaded at a dock", "road markings receding in perspective",
    "a wheel and tyre in dramatic light", "a container yard from above",
    "headlights on a highway at blue hour", "a rear view mirror with open road",
  ]),
  c("security", "Security", "deep charcoal, alert amber, steel and off-white", [
    "a security camera against a clean wall", "a control room with monitor glow",
    "a keypad entry panel, macro", "a locked steel door in low light",
    "a floodlit building exterior at night", "a badge reader beside a glass door",
    "a night-time car park under lights", "a padlock and chain in raking light",
    "a fence line at dusk", "an alarm panel on a pale wall",
  ]),
  c("church", "Church", "warm stone, deep burgundy, gold and cream", [
    "sunlight through stained glass onto stone", "wooden pews in soft light",
    "a stone archway in a quiet nave", "candles glowing on a stand",
    "an open hymn book on wood", "a bell tower against clear sky",
    "a simple wooden cross in warm light", "a stone floor with long shadows",
    "an organ pipe façade in soft focus", "a churchyard path in morning mist",
  ]),
  c("bakery-cafe", "Bakery & Cafe", "warm terracotta, cream, espresso and olive", [
    "fresh loaves cooling on a rack", "espresso pouring into a white cup",
    "croissants on a wooden board", "a cafe counter with pastries under glass",
    "flour dusted across a work surface", "a warm cafe interior with pendant lights",
    "dough being shaped by hand", "coffee beans spilling from a scoop",
    "a slice of cake on a ceramic plate", "a bakery window at golden hour",
  ]),
  c("spa-massage", "Spa & Massage", "soft sage, warm stone, cream and eucalyptus", [
    "rolled towels and river stones", "a massage table in a calm dim room",
    "eucalyptus in a steamy shower", "candles and oils on a wooden tray",
    "a stone bowl of water with petals", "soft linen draped over a bench",
    "a quiet spa corridor in warm light", "hands pouring oil into a palm",
    "steam rising in a dim treatment room", "orchids beside folded towels",
  ]),
  c("tutoring", "Tutoring", "study blue, warm cream, sage and charcoal", [
    "open textbooks on a wooden desk", "a pencil and notepad in daylight",
    "a bright study corner with a lamp", "a chalkboard with clean empty surface",
    "stacked books beside a mug", "a library aisle in soft focus",
    "handwritten notes on ruled paper", "a globe on a bookshelf",
    "a laptop and notebook on a desk", "sunlight across an open book",
  ]),
  c("event-planning", "Event Planning", "champagne gold, deep aubergine, blush and ivory", [
    "a styled table setting with candles", "string lights over an outdoor evening",
    "a floral centrepiece on linen", "stacked chairs in an empty venue",
    "a seating plan card on a table", "a marquee interior with draped fabric",
    "champagne glasses stacked in a tower", "confetti suspended against dark",
    "a dance floor with warm uplighting", "gift boxes with ribbon in soft focus",
  ]),
  c("marketing-agency", "Marketing Agency", "electric cobalt, off-black, bone and hot coral", [
    "colour swatch fans on a white desk", "a mood board pinned with samples",
    "printed collateral laid out in a grid", "a tablet and stylus on a clean desk",
    "bold overlapping paper shapes", "a bright studio with a long work table",
    "halftone printing dots in macro", "sticky notes across a glass wall",
    "abstract gradients on a screen", "a camera and laptop on a desk",
  ]),
  c("nonprofit", "Nonprofit", "hopeful teal, warm coral, sand and deep slate", [
    "hands cupped together in warm light", "volunteers packing supply boxes",
    "a community garden being tended", "a group planting a young tree",
    "donated goods sorted into crates", "a community hall with chairs in a circle",
    "open hands offering a seedling", "a sunrise over an open field",
    "hands painting a mural together", "a supportive hand on a shoulder",
  ]),
  c("healthcare", "Healthcare", "clinical teal, clean white, soft grey and navy", [
    "a stethoscope on a white surface", "a bright clinical consulting room",
    "a calm clinic waiting area", "medical charts and a tablet on white",
    "gloved hands preparing an instrument", "a hospital corridor in soft daylight",
    "a blood pressure cuff on a desk", "a clean examination table by a window",
    "pill organisers on a pale counter", "a nurse station in soft focus",
  ]),
  c("beauty-salon", "Beauty Salon", "blush pink, deep plum, champagne gold and off-white", [
    "a salon chair in a bright minimal interior", "makeup brushes fanned on pale marble",
    "a washing station in soft daylight", "nail polish bottles on a mirrored tray",
    "hair styling tools on a white counter", "soft-focus hair with warm backlight",
    "cosmetic jars arranged on stone", "a salon mirror with warm bulbs",
    "lash tools on blush fabric", "a bright reception with fresh flowers",
  ]),
  c("creative-agency", "Creative Agency", "off-black, bone, electric blue and warm coral", [
    "a studio wall of pinned prints", "an angled desk lamp over a sketchpad",
    "layered translucent acetate sheets", "a long communal work table",
    "type specimen sheets on white", "paint and ink on a print bed",
    "a camera and notebook on concrete", "abstract paper folds with hard shadow",
    "colour chips scattered on a desk", "a bright studio with tall windows",
  ]),
  c("general-corporate", "General Corporate", "deep navy, warm grey, bone and brushed steel", [
    "a glass office tower from below", "a clean boardroom with a long table",
    "a modern lobby with an architectural staircase", "a laptop and coffee on a minimal desk",
    "a city skyline at dusk from a window", "brushed steel and glass detail",
    "an empty meeting room in morning light", "stacked documents on a walnut desk",
    "soft light through office blinds", "a corridor with glass partitions",
  ]),
];
