/**
 * The rest of the card-template taxonomy, matching the categories a customer expects to browse.
 *
 * Phase 3 is the remaining top-level trades and sectors. Phase 4 is the "General" styles, which are
 * different in kind: they are not an industry with subject matter, they are a look. So their
 * subjects are materials, textures and abstract compositions rather than a trade being photographed.
 *
 * Kept in its own module purely so the generator file stays readable.
 */

export interface BedCategory {
  slug: string;
  label: string;
  phase: 1 | 2 | 3 | 4;
  subjects: string[];
  palette: string;
}

const cat = (
  slug: string, label: string, phase: 3 | 4, palette: string, subjects: string[]
): BedCategory => ({ slug, label, phase, palette, subjects });

export const EXTRA_CATEGORIES: BedCategory[] = [
  // ── Phase 3: remaining sectors ──────────────────────────────────────────────
  cat("appointment-cards", "Appointment Cards", 3, "calm sage, clean white, soft slate and warm grey", [
    "a clean desk calendar page in soft daylight",
    "a minimal appointment book with a pen resting on it",
    "a wall clock face in soft focus against a pale wall",
    "an uncluttered reception desk with a small plant",
    "a tidy diary spread with blank ruled lines",
    "soft neutral fabric texture with gentle folds",
    "a pale wooden surface with subtle grain",
    "a frosted glass panel with diffused light",
    "a simple potted plant against a plain wall",
    "a folded linen napkin on pale stone",
  ]),
  cat("design-marketing", "Design & Marketing", 3, "electric cobalt, off-black, bone white and hot coral", [
    "colour swatch fans spread on a white desk",
    "a designer workspace with a tablet and stylus",
    "bold overlapping geometric paper shapes",
    "printed brand collateral laid out in a flat grid",
    "a screen showing abstract colourful gradients",
    "paint rollers and ink on a print bed",
    "layered translucent acetate sheets",
    "a mood board pinned with fabric and colour chips",
    "macro of halftone printing dots on paper",
    "abstract paper folds casting hard shadows",
  ]),
  cat("education-childcare", "Education & Child Care", 3, "friendly primary blue, sunny yellow, grass green and cream", [
    "colourful wooden building blocks on a light floor",
    "stacked children books in bright colours",
    "a bright classroom with small chairs and tables",
    "crayons and coloured pencils scattered neatly",
    "a clean chalkboard texture with empty surface",
    "painted handprints on paper in bright colours",
    "a sunny playground in soft focus",
    "wooden alphabet tiles arranged loosely",
    "a cosy reading corner with cushions",
    "paper craft shapes in bright colours",
  ]),
  cat("entertainment-arts", "Entertainment & Arts", 3, "deep aubergine, stage gold, ink black and warm ivory", [
    "stage spotlights against a dark theatre backdrop",
    "a grand piano keyboard in dramatic light",
    "paint brushes in jars in an artist studio",
    "red velvet theatre curtains with deep folds",
    "a microphone on a dark stage",
    "an artist palette thick with oil paint",
    "a concert lighting rig with warm bokeh",
    "a violin resting on sheet music",
    "a gallery wall with blank framed canvases",
    "a film reel and camera in moody light",
  ]),
  cat("financial-services", "Financial Services", 3, "deep navy, forest green, warm grey and brushed brass", [
    "a modern bank building facade in clean light",
    "a fountain pen resting on a document",
    "an abstract upward line graph on a dark surface",
    "stacked coins in shallow focus",
    "a calculator and ledger on a walnut desk",
    "a glass office tower reflecting sky",
    "a safe deposit door in brushed steel",
    "a handshake in a bright office",
    "a clean minimal desk with laptop and coffee",
    "a marble and brass texture study",
  ]),
  cat("floral-greenery", "Floral & Greenery", 3, "soft blush, deep eucalyptus, cream and terracotta", [
    "a loose bouquet of garden roses on linen",
    "eucalyptus stems against a pale wall",
    "a florist bench with cut stems and twine",
    "dried flowers in muted tones",
    "tropical monstera leaves in soft light",
    "a flower market stall bursting with colour",
    "a single peony macro with dewdrops",
    "wildflowers in a meadow at golden hour",
    "potted plants on a sunlit windowsill",
    "pressed botanical specimens on paper",
  ]),
  cat("holidays", "Holidays", 3, "deep evergreen, warm gold, cranberry and snow white", [
    "warm string lights against a dark background",
    "pine branches and cones on a wooden surface",
    "wrapped gifts with ribbon in warm light",
    "a frosted window with soft bokeh beyond",
    "candles glowing on a festive table",
    "snowflakes falling against dark sky",
    "a wreath on a painted door",
    "a warm fireside glow with soft shadows",
    "a festive table setting with greenery",
    "gold baubles in shallow focus",
  ]),
  cat("law-politics", "Law, Public Safety & Politics", 3, "deep burgundy, navy, parchment and antique brass", [
    "classical courthouse columns in strong light",
    "law books on a dark wooden shelf",
    "a gavel resting on a polished bench",
    "a national flag in soft folds",
    "a formal boardroom with leather chairs",
    "scales of justice in silhouette",
    "an official building dome against sky",
    "a fountain pen and formal documents",
    "marble steps and a brass railing",
    "an office bookshelf with legal volumes",
  ]),
  cat("non-profit", "Non-Profit", 3, "hopeful teal, warm coral, soft sand and deep slate", [
    "hands cupped together in warm light",
    "a community garden being tended",
    "volunteers packing supply boxes",
    "a group planting a young tree",
    "open hands offering a small seedling",
    "a community hall with people gathered",
    "donated goods sorted into crates",
    "a sunrise over an open field",
    "hands painting together at a table",
    "a supportive hand on a shoulder in soft focus",
  ]),
  cat("pets-animals", "Pets & Animals", 3, "warm caramel, soft sky blue, cream and charcoal", [
    "a golden retriever in soft outdoor light",
    "a cat curled asleep on a knitted blanket",
    "a dog paw resting in a human hand",
    "grooming brushes and pet supplies",
    "a puppy playing on grass",
    "a clean bright veterinary examination room",
    "dog leads hanging on hooks",
    "a horse profile in golden hour light",
    "a bird perched on a branch",
    "pet bowls on a tiled floor",
  ]),
  cat("publishing", "Publishing", 3, "ink black, warm paper, deep red and antique gold", [
    "an open book with visible page texture",
    "stacked hardback books seen spine on",
    "a typewriter key macro",
    "printing press type blocks in a tray",
    "a manuscript page with handwritten marks",
    "a library shelf receding into soft focus",
    "fresh printed sheets on a press bed",
    "a fountain pen on cream paper",
    "folded newspaper texture in macro",
    "a reading nook with warm lamp light",
  ]),
  cat("sports-fitness", "Sports & Fitness", 3, "energetic lime, deep charcoal, electric blue and white", [
    "a barbell loaded on a gym floor",
    "running shoes on a track in morning light",
    "a basketball on a polished court",
    "dumbbells racked in a modern gym",
    "a cyclist silhouetted against sunrise",
    "a swimming pool lane seen from above",
    "boxing gloves hanging on a hook",
    "a yoga mat rolled in a bright studio",
    "a football on turf with stadium bokeh",
    "a stopwatch and whistle on a bench",
  ]),
  cat("transportation", "Transportation", 3, "steel blue, safety yellow, asphalt grey and white", [
    "a haulage truck on an open highway at dusk",
    "a container port with stacked freight",
    "an aircraft wing above cloud cover",
    "a delivery van in a clean urban street",
    "a railway track receding into the distance",
    "a warehouse loading dock with bay doors",
    "a fleet of trucks in a depot at dawn",
    "a ship bow cutting through water",
    "a logistics hub with pallets and forklifts",
    "road markings receding in perspective",
  ]),
  cat("travel-tourism", "Travel & Tourism", 3, "ocean teal, sunset coral, sand and deep indigo", [
    "a tropical beach with turquoise water",
    "a vintage suitcase and a world map",
    "an aircraft window view over mountains",
    "a winding coastal road at golden hour",
    "a passport and boarding pass on a desk",
    "a European street cafe in warm light",
    "mountain peaks above cloud",
    "a hotel pool at sunset",
    "a camera and travel journal on a table",
    "a harbour with moored boats at dawn",
  ]),

  // ── Phase 4: the General styles ─────────────────────────────────────────────
  cat("general-colorful", "General / Colorful", 4, "saturated multi-colour across the spectrum, high energy", [
    "overlapping translucent colour circles",
    "a bold rainbow gradient mesh",
    "confetti scattered on white",
    "paint splashes in many colours",
    "colour-blocked geometric planes",
    "bright liquid ink swirling in water",
    "stacked coloured paper layers",
    "a vivid abstract colour field",
    "colourful powder pigment bursting",
    "bright neon light tubes on dark",
  ]),
  cat("general-credit-card", "General / Credit Card Style", 4, "brushed metal, deep black, chrome and subtle holographic", [
    "a brushed metal surface with fine horizontal grain",
    "a dark carbon fibre weave in macro",
    "polished chrome with soft reflections",
    "matte black with a subtle embossed pattern",
    "a holographic foil sheen across dark metal",
    "concentric machined metal circles",
    "dark titanium with a light sweep",
    "a metallic gradient from graphite to silver",
    "a subtle guilloche engraving pattern",
    "black leather grain with a metallic edge",
  ]),
  cat("general-elegant", "General / Elegant", 4, "ivory, deep charcoal, soft gold and dusty rose", [
    "cream silk with soft draping folds",
    "gold leaf flecks on off-white",
    "a marble surface with fine veining",
    "soft satin in warm neutral tones",
    "delicate lace texture close up",
    "champagne bokeh against dark",
    "embossed cream paper texture",
    "a pale feather in macro",
    "fine gold filigree on ivory",
    "a softly lit pearl surface",
  ]),
  cat("general-funny", "General / Funny", 4, "playful pop colours, bright cyan, hot pink and sunshine yellow", [
    "cartoon style speech bubble shapes",
    "bouncy rounded abstract blobs",
    "a bright polka dot pattern",
    "a squiggly hand drawn line pattern",
    "playful confetti shapes on a bright ground",
    "a comic style halftone burst",
    "stacked colourful rubber shapes",
    "a cheerful abstract character form",
    "a zany zigzag pattern in bright colours",
    "bright balloons against clear sky",
  ]),
  cat("general-geometric", "General / Geometric", 4, "deep ink, bone, single burnt orange accent", [
    "overlapping translucent triangles",
    "a precise isometric cube grid",
    "concentric circles in flat colour",
    "hard edge diagonal colour bands",
    "a bauhaus style composition of primitives",
    "nested squares receding inward",
    "a hexagonal tessellation pattern",
    "sharp angular paper folds with shadow",
    "a grid of dots varying in scale",
    "intersecting straight lines forming planes",
  ]),
  cat("general-loyalty", "General / Loyalty Cards", 4, "warm amber, deep espresso, cream and soft gold", [
    "a row of embossed circular stamps on card",
    "a subtle repeating star pattern on kraft",
    "warm coffee toned paper texture",
    "a punch card grid of empty circles",
    "gold foil dots on deep brown",
    "a simple repeating badge motif",
    "warm cardboard texture close up",
    "a ticket edge perforation detail",
    "stacked kraft cards in soft light",
    "a wax seal impression on paper",
  ]),
  cat("general-minimalist", "General / Minimalist", 4, "off-white, soft grey, one thin black rule", [
    "a plain off-white surface with a single soft shadow",
    "a fine hairline rule across empty space",
    "subtle paper grain in raking light",
    "a soft gradient from white to pale grey",
    "one small dark square on a white field",
    "a gently folded paper edge with shadow",
    "matte white plaster texture",
    "a single thin line dividing empty space",
    "soft diffused light across a blank surface",
    "understated linen texture in white",
  ]),
  cat("general-modern", "General / Modern", 4, "cool slate, crisp white, electric blue accent", [
    "a sleek glass and steel architectural detail",
    "a smooth gradient from slate to white",
    "a clean concrete surface with sharp shadow",
    "brushed aluminium with directional light",
    "a minimal architectural corner in daylight",
    "frosted acrylic panels layered",
    "a crisp shadow cast across pale concrete",
    "polished terrazzo surface in macro",
    "a contemporary facade with clean lines",
    "a soft studio gradient backdrop",
  ]),
  cat("general-nature", "General / Nature & Landscapes", 4, "forest green, sky blue, stone grey and warm sand", [
    "a misty mountain range at dawn",
    "a calm lake reflecting pine trees",
    "sunlight filtering through a forest canopy",
    "rolling green hills under open sky",
    "a rocky coastline with breaking waves",
    "a desert dune ridge at golden hour",
    "a river winding through autumn woodland",
    "a wildflower meadow under blue sky",
    "snow covered peaks in clear light",
    "a lone tree on an open plain",
  ]),
  cat("general-patriotic", "General / Patriotic", 4, "deep navy, true red, crisp white and silver", [
    "a flag rippling in soft wind",
    "abstract red white and blue colour bands",
    "a field of stars on deep navy",
    "stripes receding in perspective",
    "a monument silhouette against sky",
    "bunting in patriotic colours",
    "fireworks against a dark sky",
    "an eagle silhouette in soft focus",
    "weathered painted stars on wood",
    "a windswept flag against clouds",
  ]),
  cat("general-patterns", "General / Patterns", 4, "two-tone with a single accent, high contrast", [
    "a seamless herringbone pattern",
    "a repeating art deco fan motif",
    "a fine diagonal pinstripe texture",
    "a chevron pattern in two tones",
    "an organic terrazzo speckle pattern",
    "repeating scallop shapes",
    "woven basket texture in macro",
    "a subtle damask motif",
    "an interlocking circle lattice",
    "a hand printed block pattern on paper",
  ]),
  cat("general-popular", "General / Popular", 4, "versatile charcoal, warm white, single teal accent", [
    "a clean gradient backdrop with a soft vignette",
    "subtle textured paper in a neutral tone",
    "a soft abstract colour wash",
    "gentle bokeh against a dark ground",
    "a smooth studio backdrop with light falloff",
    "a simple diagonal colour split",
    "soft cloud texture in neutral tones",
    "fine linen weave in macro",
    "a calm abstract gradient field",
    "understated marble in grey and white",
  ]),
  cat("general-rsvp", "General / RSVP", 4, "soft blush, ivory, sage and antique gold", [
    "delicate botanical line art with open space on ivory",
    "a soft watercolour wash in blush tones",
    "pressed petals on cream paper",
    "a fine gold border on off-white",
    "a subtle deckled paper edge",
    "soft focus candlelight bokeh",
    "a eucalyptus sprig on pale linen",
    "a wax seal on an ivory envelope",
    "gently marbled paper in soft tones",
    "a fine calligraphy nib and ink pot",
  ]),
  cat("general-solid", "General / Solid Colors", 4, "single saturated field with subtle tonal depth", [
    "a deep teal field with a subtle tonal shift",
    "a rich burgundy surface with soft light",
    "a saturated cobalt colour field",
    "warm mustard flat colour with a gentle gradient",
    "deep forest green with a soft vignette",
    "a dusty rose field with fine grain",
    "charcoal near black with a subtle sheen",
    "a burnt orange flat colour surface",
    "deep plum with soft light falloff",
    "a muted sage flat colour field",
  ]),
  cat("general-thank-you", "General / Thank You", 4, "warm cream, soft terracotta, sage and gold", [
    "soft dried florals on warm linen",
    "a simple ribbon bow on kraft paper",
    "gentle warm light across blank card stock",
    "a small wrapped parcel with twine",
    "soft focus warm bokeh in gold tones",
    "pressed leaves on textured paper",
    "a plain envelope with a wax seal",
    "warm sunlight across a blank page",
    "delicate petals scattered on cream",
    "a sprig of dried lavender on pale paper",
  ]),
  cat("general-vintage", "General / Vintage", 4, "sepia, faded teal, aged paper and oxblood", [
    "aged paper with foxing and worn edges",
    "a vintage typewriter in warm light",
    "old postage stamps arranged on paper",
    "a weathered wooden surface with peeling paint",
    "an antique map detail in sepia tones",
    "a retro camera on aged leather",
    "faded floral wallpaper texture",
    "an old ledger page with ruled lines",
    "vintage botanical illustration texture",
    "a worn leather book cover in macro",
  ]),
];
