import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL ?? "" });
const db = new PrismaClient({ adapter });
const DRY_RUN = process.argv.includes("--dry-run");

// Templates are procedurally generated by stamping a small set of layout archetypes across ~20
// fake industries (see CardTemplate.featured comment in schema.prisma). Sampled thumbnails confirm
// the layout, colors, and decorative elements are pixel-identical across industries within an
// archetype — only the placeholder name/text differs — so "unique design" collapses to one row per
// (product, archetype), except rigid signs where the die-cut shape is a genuinely different product.
async function main() {
  const products = ["BUSINESS_CARD", "POSTCARD", "BANNER", "RIGID_SIGN"] as const;
  let grandTotalBefore = 0;
  let grandTotalAfter = 0;

  for (const product of products) {
    const rows = await db.cardTemplate.findMany({
      where: { product, active: true },
      select: { id: true, slug: true, tags: true, industry: true, featured: true },
    });

    const groups = new Map<string, typeof rows>();
    for (const r of rows) {
      const key = product === "RIGID_SIGN" ? `${r.tags[2]}|${r.tags[3]}` : r.tags[2];
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push(r);
    }

    console.log(`\n=== ${product}: ${rows.length} active rows -> ${groups.size} unique designs ===`);
    grandTotalBefore += rows.length;
    grandTotalAfter += groups.size;

    for (const [key, members] of groups) {
      const featuredMembers = members.filter((m) => m.featured);
      const pickFrom = featuredMembers.length > 0 ? featuredMembers : members;
      const keeper =
        pickFrom.find((m) => m.industry === "real-estate") ??
        [...pickFrom].sort((a, b) => a.industry.localeCompare(b.industry))[0];

      const dropIds = members.filter((m) => m.id !== keeper.id).map((m) => m.id);

      if (!DRY_RUN) {
        await db.cardTemplate.update({ where: { id: keeper.id }, data: { active: true, featured: true } });
        if (dropIds.length > 0) {
          await db.cardTemplate.updateMany({ where: { id: { in: dropIds } }, data: { active: false, featured: false } });
        }
      }

      console.log(`  ${key}: kept ${keeper.slug} (${members.length} -> 1)`);
    }
  }

  console.log(`\nTotal active templates: ${grandTotalBefore} -> ${grandTotalAfter}`);
  await db.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
