"use client";

import { useEffect, useRef, useState } from "react";
import { Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * The large product preview that sits to the left of the configurator.
 *
 * This replaces the thumbnail that used to live inside the order summary rail. That thumbnail was
 * about 260px wide in a 340px column, which is smaller than the card it depicts - and for an
 * uploaded PDF it was handed the raw file URL and dropped into an <img>, so what the customer saw
 * of their own artwork was whatever the storage host happened to rasterise for a preview, scaled
 * down again. People could not read their own card.
 *
 * Three things fix that here: the pane owns a whole column rather than a rail, PDFs are rendered
 * properly with pdf.js at device resolution, and the frame takes the aspect ratio of the piece
 * actually selected - so choosing Vertical visibly turns the card on its end instead of leaving a
 * landscape thumbnail behind.
 */

export interface ProductPreviewPaneProps {
  /** Inline SVG of a design built in the studio or generated by AI. Wins over everything else. */
  svg?: string | null;
  /** A customer's uploaded file: an image, or a PDF to rasterise. */
  fileUrl?: string | null;
  fileName?: string | null;
  /** Stock product photography, shown until there is artwork to show instead. */
  fallbackImageUrl?: string;
  alt: string;
  /** Finished size, used for the frame's aspect ratio. */
  widthIn?: number;
  heightIn?: number;
  /** Rendered under the frame - "Front", the file name, the template name. */
  caption?: string | null;
  className?: string;
}

const isPdf = (url?: string | null, name?: string | null) =>
  Boolean(/\.pdf(\?|#|$)/i.test(url ?? "") || /\.pdf$/i.test(name ?? ""));

export function ProductPreviewPane({
  svg, fileUrl, fileName, fallbackImageUrl, alt, widthIn, heightIn, caption, className,
}: ProductPreviewPaneProps) {
  /*
   * Clamped, because the aspect ratio comes from real print sizes and some of them are extreme: a
   * 96" x 48" banner is 2:1 and fine, but a 36" x 72" portrait banner left to itself makes a column
   * twice as tall as the viewport. Anything outside these bounds is shown letterboxed instead.
   */
  const ratio = widthIn && heightIn && widthIn > 0 && heightIn > 0
    ? Math.min(Math.max(widthIn / heightIn, 0.5), 2.5)
    : undefined;

  return (
    <div className={cn("lg:sticky lg:top-24", className)}>
      {/*
        Capped in height as well as ratio.

        The aspect ratio alone is not enough: a vertical business card is 0.58:1, which in a 716px
        column is a frame 1,253px tall - taller than the viewport, so the options beside it were
        pushed off screen and the customer scrolled past an empty white rectangle to reach them.
        Anything taller than the cap letterboxes inside the frame instead of stretching the page.
      */}
      <div
        className="relative mx-auto w-full overflow-hidden rounded-2xl border-2 border-kc-border bg-white shadow-[0_2px_24px_-12px_rgba(12,10,9,0.18)]"
        style={
          ratio
            ? {
                aspectRatio: String(ratio),
                // Narrow the frame rather than clamp its height: capping height against a fixed
                // width would hold the box and squash the ratio, which is the one thing this frame
                // exists to be honest about.
                maxWidth: ratio < 1 ? `calc(${ratio} * min(68vh, 620px))` : undefined,
              }
            : undefined
        }
      >
        {/* A tint behind the artwork, so a white card on a white page still reads as an object. */}
        <div className="absolute inset-0 bg-[linear-gradient(135deg,#F7F7F8_0%,#EFEFF1_100%)]" />
        <div className="relative flex h-full w-full items-center justify-center p-4 sm:p-6">
          <PreviewBody
            svg={svg}
            fileUrl={fileUrl}
            fileName={fileName}
            fallbackImageUrl={fallbackImageUrl}
            alt={alt}
          />
        </div>
      </div>
      {caption && <p className="mt-3 text-center text-xs text-kc-muted">{caption}</p>}
    </div>
  );
}

function PreviewBody({
  svg, fileUrl, fileName, fallbackImageUrl, alt,
}: Pick<ProductPreviewPaneProps, "svg" | "fileUrl" | "fileName" | "fallbackImageUrl" | "alt">) {
  if (svg) {
    return (
      <div
        // The SVG carries pixel width/height at its render DPI, which would overflow the frame; the
        // viewBox is in inches, so constraining both axes shows the whole piece at true proportions.
        className="h-full w-full [&>svg]:h-full [&>svg]:w-full [&>svg]:object-contain drop-shadow-[0_8px_24px_rgba(12,10,9,0.18)]"
        role="img"
        aria-label={alt}
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    );
  }

  if (fileUrl && isPdf(fileUrl, fileName)) {
    return <PdfPreview url={fileUrl} alt={alt} />;
  }

  const src = fileUrl ?? fallbackImageUrl;
  if (!src) return null;
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt={alt}
      className="max-h-full max-w-full object-contain drop-shadow-[0_8px_24px_rgba(12,10,9,0.18)]"
    />
  );
}

/**
 * Renders page 1 of a PDF with pdf.js, loaded on demand so the library only ships to the people who
 * uploaded one.
 *
 * Rasterised at the element's own displayed size multiplied by devicePixelRatio, rather than at a
 * fixed scale, so the preview is sharp on a retina display and is not needlessly enormous on a
 * phone. This is the part that was missing: previously the PDF was never rasterised for this
 * preview at all, it was simply pointed at with an <img>.
 */
function PdfPreview({ url, alt }: { url: string; alt: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const boxRef = useRef<HTMLDivElement>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");

  useEffect(() => {
    let cancelled = false;
    let cleanup: (() => void) | undefined;
    (async () => {
      try {
        const pdfjs = await import("pdfjs-dist");
        pdfjs.GlobalWorkerOptions.workerSrc = new URL(
          "pdfjs-dist/build/pdf.worker.min.mjs",
          import.meta.url
        ).toString();
        const task = pdfjs.getDocument({ url });
        cleanup = () => void task.destroy();
        const doc = await task.promise;
        if (cancelled) return;
        const page = await doc.getPage(1);
        const canvas = canvasRef.current;
        if (!canvas || cancelled) return;

        const base = page.getViewport({ scale: 1 });
        // Target the real drawn width, at device pixels, with a floor so a narrow phone still gets
        // something legible and a ceiling so a huge page does not allocate an unreasonable canvas.
        const cssWidth = boxRef.current?.clientWidth ?? 640;
        const dpr = typeof window !== "undefined" ? Math.min(window.devicePixelRatio || 1, 3) : 1;
        const targetPx = Math.min(Math.max(cssWidth * dpr, 900), 3000);
        const viewport = page.getViewport({ scale: targetPx / base.width });

        canvas.width = Math.round(viewport.width);
        canvas.height = Math.round(viewport.height);
        const ctx = canvas.getContext("2d");
        if (!ctx) return;
        await page.render({ canvas, canvasContext: ctx, viewport }).promise;
        if (!cancelled) setState("ready");
      } catch {
        if (!cancelled) setState("error");
      }
    })();
    return () => {
      cancelled = true;
      cleanup?.();
    };
  }, [url]);

  return (
    <div ref={boxRef} className="relative flex h-full w-full items-center justify-center">
      <canvas
        ref={canvasRef}
        aria-label={alt}
        role="img"
        className={cn(
          "max-h-full max-w-full object-contain drop-shadow-[0_8px_24px_rgba(12,10,9,0.18)]",
          state !== "ready" && "invisible"
        )}
      />
      {state !== "ready" && (
        <div className="absolute inset-0 flex items-center justify-center text-sm text-kc-dark/70">
          {state === "loading" ? (
            <span className="flex items-center gap-2">
              <Loader2 className="h-4 w-4 animate-spin" /> Rendering your PDF
            </span>
          ) : (
            <span className="px-4 text-center">
              We couldn&apos;t render a preview, but we did read its size. A designer will check it
              before print.
            </span>
          )}
        </div>
      )}
    </div>
  );
}
